site_name: Animpy Official documentation
docs_dir: 'animpy-docs/docs'
theme:
  name: material
  palette:
    scheme: slate 
    primary: deep orange

nav:
  - Home: index.md
  - Features: features.md
  - API Reference: api.md

repo_url: https://github.com/13DoesPython/animpy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('.')