site_name: Animpy Official documentation
docs_dir: 'docs'
theme:
  name: material
  palette:
    scheme: slate 
    primary: deep orange

nav:
  - Home: index.md
  - Features: features.md
  - API Reference: api.md

repo_url: https://github.com/13DoesPython/animpy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            paths: ["."]